### ISSUE TITLE
Issue with raw data

### ISSUE THREAD

**Issue by laterz-f** [Aleksobrad/single-cell-rcc-pipeline#1]
Super interesting work!

I am trying to download the raw data but I am experiencing issues with some files, specifically the ones present in the following folders:
190524_CHARLES_NIVI_10_HUMAN_10X
190603_CHARLES_NIVI_9_HUMAN_10X
190606_CHARLES_NIVI_8_HUMAN_10X
190825_VICTOR_VICTOR_1_HUMAN_10X

At least for the files corresponding to Tumors CD45+ cells, I cannot access the data. 
If I try to import them in R using the Read10X function from Seurat I get an error saying that the files are not in the specified format. This is the error I get:

Error in readMM(file = matrix.loc) : file is not a MatrixMarket file

If I try to open the files in a different way (e.g. trying to unzip them) I get an error saying that it is not possible to unzip them.
This does not occur with the files present in the other folders - I can open them and use them. 
Could you help me with this issue?

Thanks in advance!

**Comment by Aleksobrad** [comment]
Having difficulty reproducing this issue on my end-- the matrix.mtx.gz
files in these directories all appear to be in MatrixMarket format and load
fine from fresh install on my machine and for a few of my colleagues (check
matrix files on your local install for the header line "%%MatrixMarket
matrix coordinate integer general"). Does the problem still occur if you
download data files individually? There may be some issue arising on your
end from git-lfs but I am uncertain.

If the problem persists another good troubleshooting option would be to
install from "singlecell_rawdata.zip" at the Mendeley data repository:
https://data.mendeley.com/datasets/nc9bc8dn4m/1
This exactly mirrors the data uploaded to the github and doesn't have the
same file-size restrictions on data which git sometimes imposes. Please let
me know if you have any issues with the data on the Mendeley repository.

Best,
Aleks Obradovic

**Comment by laterz-f** [comment]
Thank you for the fast and kind reply!
By downloading the data from the Mendeley repository I do not experience any issue, everything works just fine.
