### ISSUE TITLE
where is the data of the file sc_nets?

### ISSUE THREAD

**Issue by liu-zzu** [Aleksobrad/single-cell-rcc-pipeline#3]
Hello, 
When I run the R script singlecell_gex_viper_analysis.R, there is an error.
where is the data of the file sc_nets?
" filenames <- list.files("sc_nets/", pattern="Patient*", full.names=TRUE)"
Thanks !!!

**Comment by Aleksobrad** [comment]
sc_nets is the subdirectory available at
https://github.com/Aleksobrad/single-cell-rcc-pipeline/tree/master/sc_nets

**Comment by liu-zzu** [comment]
Thank you for your kind reply!
Between lines 1320 and 1340 in the R script “singlecell_gex_viper_analysis.R”, the code that generates the ARACNe network results seems to be missing there. Where is the code that generates the data in sc_nets file ?
Best wishes!

**Comment by Aleksobrad** [comment]
The code that generates the ARACNe networks is not implemented in R, and
instead uses the java implementation of the ARACNe-AP tool from
https://github.com/califano-lab/ARACNe-AP

ARACNE is executed on the .rds files created in local environment by the
makeCMFA() function within the R script. For each of these files ARACNe is
run on our high-performance computing cluster to improve speed by
parallelization. We describe this workflow in more detail at
https://github.com/califano-lab/PISCES and in
https://www.biorxiv.org/content/10.1101/2021.05.20.445002v2

We are working on future implementations of ARACNe executable directly from
R, but at the moment ARACNe must be run separately within the overall
workflow and requires a significant amount of compute time, or else a
pre-computed set of ARACNe networks can be provided as input to downstream
VIPER inferences.

**Comment by liu-zzu** [comment]
Thank you for your prompt reply！
Maybe you can set up a separate R script for parallel computing ARACNe network with library(parallel) in R。
Single-cell protein activity inference is very valuable work. And if it is easy to use, it would be universally welcomed.
Best wishes!

**Comment by baoyulinn** [comment]
Where is the Rscript "singlecell_gex_viper_analysis.R" ? 
Thank you!

**Comment by Aleksobrad** [comment]
https://github.com/Aleksobrad/single-cell-rcc-pipeline/blob/master/singlecell_gex_viper_analysis.R
